#!/usr/bin/env node
'use strict';

// Keep generated mobile projects reproducible. Platform customizations belong here,
// not in ignored src-tauri/gen directories, which can be regenerated by the CLI.
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const nativeDir = path.resolve(__dirname, '..');
const tauriDir = path.join(nativeDir, 'src-tauri');
const androidUpdatesDir = path.join(nativeDir, 'android-updates');
const updateProviderStart = '        <!-- ECL Android updates provider: managed by mobile.cjs -->';
const updateProviderEnd = '        <!-- End ECL Android updates provider -->';
const networkConfig = `<?xml version="1.0" encoding="utf-8"?>
<!-- Managed by scripts/mobile.cjs. HTTPS everywhere except device loopback. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">127.0.0.1</domain>
    </domain-config>
</network-security-config>
`;

function command(program, args, options = {}) {
  const result = spawnSync(program, args, { cwd: nativeDir, stdio: 'inherit', ...options });
  if (result.error) throw new Error(`${program}: ${result.error.message}`);
  if (result.status !== 0) throw new Error(`${program} exited with ${result.status ?? result.signal}`);
  return result;
}

function checkCommand(program, args, message) {
  const result = spawnSync(program, args, { cwd: nativeDir, encoding: 'utf8' });
  if (result.error || result.status !== 0) throw new Error(message);
  return `${result.stdout || ''}${result.stderr || ''}`.trim();
}

function preflight(platform) {
  checkCommand('cargo', ['--version'], 'Install Rust with rustup and add Cargo to PATH: https://v2.tauri.app/start/prerequisites/');
  checkCommand('rustup', ['--version'], 'rustup is required to install the Android/iOS Rust targets.');
  if (platform === 'android') {
    const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
    if (!sdk || !fs.existsSync(path.join(sdk, 'platform-tools'))) {
      throw new Error('Android SDK not found. Install Android Studio SDK Platform-Tools and set ANDROID_HOME to the SDK directory. See docs/NATIVE_APPS.md.');
    }
    process.env.ANDROID_HOME = sdk;
    const ndk = process.env.NDK_HOME;
    if (!ndk || !fs.existsSync(path.join(ndk, 'source.properties'))) {
      throw new Error('Android NDK not found. Install NDK (Side by side) and set NDK_HOME to its version directory, e.g. $ANDROID_HOME/ndk/27.2.12479018.');
    }
    const java = process.env.JAVA_HOME
      ? path.join(process.env.JAVA_HOME, 'bin', process.platform === 'win32' ? 'java.exe' : 'java')
      : 'java';
    const version = checkCommand(java, ['-version'], 'A JDK is required. Install JDK 17 or newer and set JAVA_HOME (CI uses JDK 21).');
    const major = version.match(/version "(?:1\.)?(\d+)/)?.[1];
    if (!major || Number(major) < 17) throw new Error('Android builds require JDK 17 or newer (CI uses JDK 21).');
  } else {
    if (process.platform !== 'darwin') throw new Error('iOS apps can only be built on macOS with the full Xcode installation.');
    checkCommand('xcodebuild', ['-version'], 'Install full Xcode, open it once, and select it with xcode-select. Command Line Tools alone cannot build iOS apps.');
    checkCommand('xcrun', ['--sdk', 'iphonesimulator', '--show-sdk-path'], 'The iOS Simulator SDK is missing. Install iOS platform support in Xcode Settings → Components.');
    checkCommand('pod', ['--version'], 'CocoaPods is missing. Install it (brew install cocoapods), then retry.');
  }
}

function addManifestEntry(xml, marker, entry) {
  if (xml.includes(marker)) return xml;
  const anchor = '    <uses-permission android:name="android.permission.INTERNET" />';
  if (!xml.includes(anchor)) throw new Error('Unknown Android manifest template: INTERNET anchor missing. Update mobile.cjs for the pinned Tauri CLI.');
  return xml.replace(anchor, `${anchor}\n${entry}`);
}

function androidUpdateChannel() {
  const configPath = path.join(nativeDir, 'update-channel.json');
  const channel = JSON.parse(fs.readFileSync(configPath, 'utf8')).androidDistribution;
  if (!['github', 'store'].includes(channel)) {
    throw new Error('update-channel.json androidDistribution must be github or store.');
  }
  if (process.env.ECL_ANDROID_UPDATE_CHANNEL && process.env.ECL_ANDROID_UPDATE_CHANNEL !== channel) {
    throw new Error('ECL_ANDROID_UPDATE_CHANNEL must match update-channel.json androidDistribution; update the compiled channel configuration first.');
  }
  return channel;
}

function patchAndroidManifest(xml, updateChannel = androidUpdateChannel()) {
  if (!['github', 'store'].includes(updateChannel)) throw new Error('Unknown Android update channel.');
  // Store distributions use their store's update mechanism. Reapplying the
  // wrapper removes our sideload permission/provider when switching channels.
  xml = xml.replace(/\s*<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"\s*\/>/g, '');
  const providerStart = xml.indexOf(updateProviderStart);
  if (providerStart >= 0) {
    const providerEnd = xml.indexOf(updateProviderEnd, providerStart);
    if (providerEnd < 0) throw new Error('Incomplete managed Android update provider.');
    xml = xml.slice(0, providerStart) + xml.slice(providerEnd + updateProviderEnd.length + (xml[providerEnd + updateProviderEnd.length] === '\n' ? 1 : 0));
  }
  if (updateChannel === 'github') {
    const provider = fs.readFileSync(path.join(androidUpdatesDir, 'manifest.xml'), 'utf8').trimEnd();
    if (xml.includes('ru.ecl.workspace.updates.UpdateFileProvider') || xml.includes('${applicationId}.ecl.updates')) {
      throw new Error('Unmanaged Android update provider found. Review it before changing mobile.cjs.');
    }
    if (!xml.includes('    </application>')) throw new Error('Unknown Android manifest template: application closing anchor missing.');
    xml = xml.replace('    </application>', `${updateProviderStart}\n${provider}\n${updateProviderEnd}\n    </application>`);
  }
  xml = addManifestEntry(xml, 'android.permission.CAMERA', '    <uses-permission android:name="android.permission.CAMERA" />');
  xml = addManifestEntry(xml, 'android.permission.RECORD_AUDIO', '    <uses-permission android:name="android.permission.RECORD_AUDIO" />');
  xml = addManifestEntry(xml, 'android.permission.MODIFY_AUDIO_SETTINGS', '    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />');
  xml = addManifestEntry(xml, 'android.hardware.camera', '    <uses-feature android:name="android.hardware.camera" android:required="false" />');
  // The system camera intent is resolved by Wry's file chooser on Android 11+.
  if (!xml.includes('android.media.action.IMAGE_CAPTURE')) {
    if (xml.includes('<queries>')) {
      xml = xml.replace('<queries>', '<queries>\n        <intent><action android:name="android.media.action.IMAGE_CAPTURE" /></intent>');
    } else {
      xml = addManifestEntry(xml, 'android.media.action.IMAGE_CAPTURE', '    <queries>\n        <intent><action android:name="android.media.action.IMAGE_CAPTURE" /></intent>\n    </queries>');
    }
  }
  if (updateChannel === 'github') {
    xml = addManifestEntry(xml, 'android.permission.REQUEST_INSTALL_PACKAGES', '    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />');
  }
  const applications = xml.match(/<application\b[^>]*>/g);
  if (!applications || applications.length !== 1) throw new Error('Expected one Android <application> element.');
  let application = applications[0];
  if (/android:networkSecurityConfig=/.test(application) && !application.includes('android:networkSecurityConfig="@xml/ecl_network_security_config"')) {
    throw new Error('An unmanaged Android networkSecurityConfig already exists. Review it before changing mobile.cjs.');
  }
  if (/android:usesCleartextTraffic=/.test(application)) {
    application = application.replace(/android:usesCleartextTraffic="[^"]*"/, 'android:usesCleartextTraffic="false"');
  } else {
    application = application.replace('<application', '<application android:usesCleartextTraffic="false"');
  }
  if (!application.includes('android:networkSecurityConfig=')) {
    application = application.replace('<application', '<application android:networkSecurityConfig="@xml/ecl_network_security_config"');
  }
  return xml.replace(applications[0], application);
}

function configureAndroid(projectDir, updateChannel = androidUpdateChannel()) {
  const manifestPath = path.join(projectDir, 'app', 'src', 'main', 'AndroidManifest.xml');
  const previous = fs.readFileSync(manifestPath, 'utf8');
  const next = patchAndroidManifest(previous, updateChannel);
  const resourceDir = path.join(projectDir, 'app', 'src', 'main', 'res', 'xml');
  const resourcePath = path.join(resourceDir, 'ecl_network_security_config.xml');
  if (fs.existsSync(resourcePath) && fs.readFileSync(resourcePath, 'utf8') !== networkConfig) {
    throw new Error(`Refusing to overwrite a modified network policy: ${resourcePath}`);
  }
  fs.mkdirSync(resourceDir, { recursive: true });
  fs.writeFileSync(resourcePath, networkConfig);
  const updatesPackageDir = path.join(projectDir, 'app', 'src', 'main', 'java', 'ru', 'ecl', 'workspace', 'updates');
  fs.mkdirSync(updatesPackageDir, { recursive: true });
  fs.copyFileSync(path.join(androidUpdatesDir, 'UpdatesPlugin.kt'), path.join(updatesPackageDir, 'UpdatesPlugin.kt'));
  fs.copyFileSync(path.join(androidUpdatesDir, 'ecl_update_paths.xml'), path.join(resourceDir, 'ecl_update_paths.xml'));
  if (next !== previous) fs.writeFileSync(manifestPath, next);
}

function checkIosPermissions() {
  const config = JSON.parse(fs.readFileSync(path.join(tauriDir, 'tauri.conf.json'), 'utf8'));
  const plist = config.bundle?.iOS?.infoPlist;
  if (!plist) throw new Error('bundle.iOS.infoPlist must reference a plist with NSCameraUsageDescription.');
  const contents = fs.readFileSync(path.resolve(tauriDir, plist), 'utf8');
  if (!contents.includes('<key>NSCameraUsageDescription</key>')) {
    throw new Error('iOS camera permission text is missing from the configured Info.plist.');
  }
}

function main(args) {
  const [platform, action, ...extra] = args;
  if (!['android', 'ios'].includes(platform) || !['init', 'build'].includes(action)) {
    throw new Error('Usage: node scripts/mobile.cjs <android|ios> <init|build> [Tauri options]');
  }
  const cli = path.join(nativeDir, 'node_modules', '@tauri-apps', 'cli', 'tauri.js');
  if (!fs.existsSync(cli)) throw new Error('Run npm ci in native/ before building.');
  if (extra.includes('--help') || extra.includes('-h')) {
    command(process.execPath, [cli, platform, action, ...extra]);
    return;
  }
  preflight(platform);
  if (platform === 'ios') checkIosPermissions();
  const projectDir = path.join(tauriDir, 'gen', platform === 'android' ? 'android' : 'apple');
  const marker = platform === 'android'
    ? path.join(projectDir, 'app', 'src', 'main', 'AndroidManifest.xml')
    : path.join(projectDir, 'project.yml');
  if (!fs.existsSync(marker)) {
    if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length) {
      throw new Error(`Incomplete generated project in ${projectDir}. Move it aside and rerun init; existing files were preserved.`);
    }
    // The native web bundle is also needed by the generated Xcode project.
    command(process.execPath, [path.join(__dirname, 'prepare-web.cjs')]);
    command(process.execPath, [cli, platform, 'init', ...(action === 'init' ? extra : ['--ci'])]);
  } else if (action === 'init') {
    console.log(`Using existing ${platform} project; applying ECL platform settings.`);
  }
  if (platform === 'android') configureAndroid(projectDir);
  if (action === 'build') command(process.execPath, [cli, platform, 'build', ...extra]);
  else console.log(`${platform} project ready at ${projectDir}`);
}

module.exports = { patchAndroidManifest, configureAndroid, androidUpdateChannel, networkConfig, main };
if (require.main === module) {
  try { main(process.argv.slice(2)); }
  catch (error) { console.error(`\nECL mobile: ${error.message}`); process.exitCode = 1; }
}
