'use strict';
// Real local API and disposable synthetic PostgreSQL; no business records.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { createTestServer } = require('./local-test-server.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const fixture = await createTestServer({ builtFrontend: process.env.DEVELOPMENT_BUILT_FRONTEND === 'true' });
  let browser;
  try {
    const { ids, request, devLogin } = fixture;
    const admin = await devLogin(ids.admin), employee = await devLogin(ids.drivers[0]);
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const errors = [];
    async function pageFor(session, viewport = { width: 1440, height: 1000 }) {
      const context = await browser.newContext({ viewport, timezoneId: 'Europe/Moscow' });
      await context.addInitScript(value => sessionStorage.setItem('ecl.session.v2', JSON.stringify({ session: value })), { ...session, rememberedDevice: false });
      const page = await context.newPage();
      page.setDefaultTimeout(15000);
      page.on('pageerror', error => errors.push(error.message));
      await page.goto(`${fixture.origin}/?section=development`);
      await page.getByRole('heading', { name: 'Разработка', exact: true }).waitFor();
      await page.waitForFunction(() => document.querySelector('[aria-label="Обновить список тикетов"]')?.disabled === false);
      return page;
    }
    const page = await pageFor(employee);
    const title = 'Не сохраняется комментарий к автомобилю';
    await page.getByRole('button', { name: /Новый тикет/ }).click();
    let dialog = page.getByRole('dialog');
    await dialog.getByLabel('Название', { exact: true }).fill(title);
    await dialog.getByLabel('Раздел приложения', { exact: true }).selectOption('fleet');
    await dialog.getByLabel('Описание', { exact: true }).fill('Нажимаю сохранить после ввода комментария. После обновления страницы текст пропадает. Ожидаю сохранения.');
    let response = page.waitForResponse(r => r.url().endsWith('/development/tickets') && r.request().method() === 'PUT');
    await dialog.getByRole('button', { name: /Создать|Сохранить/ }).click();
    const created = await response;
    assert.equal(created.status(), 200, await created.text());
    const ticket = await created.json();
    assert.equal(ticket.authorId, ids.drivers[0]);
    assert.equal(ticket.status, 'new');
    console.log('PASS employee creates a real persisted ticket in analytics');
    // Reload proves the board comes from the API, not component state.
    await page.reload();
    await page.getByText(title, { exact: true }).waitFor();
    await page.getByText(title, { exact: true }).click();
    dialog = page.getByRole('dialog');
    assert.equal(await dialog.getByLabel('Этап', { exact: true }).count(), 0);
    await dialog.getByLabel('Комментарий', { exact: true }).fill('Повторяется после повторного входа.');
    response = page.waitForResponse(r => r.url().endsWith('/development/comments') && r.request().method() === 'POST');
    await dialog.getByRole('button', { name: /Добавить комментарий|Отправить/ }).click();
    assert.equal((await response).status(), 201);
    await dialog.getByText('Повторяется после повторного входа.', { exact: true }).waitFor();
    console.log('PASS employee sees own ticket and can comment, without stage management');

    const adminPage = await pageFor(admin);
    // An old board response must not overwrite a later saved status.
    let releaseList, capturedList;
    const delayedList = new Promise(resolve => { releaseList = resolve; });
    const listCaptured = new Promise(resolve => { capturedList = resolve; });
    await adminPage.route('**/api/v1/development?**', async route => {
      const snapshot = await route.fetch(); capturedList(); await delayedList; await route.fulfill({ response: snapshot });
    }, { times: 1 });
    await adminPage.getByRole('button', { name: 'Обновить список тикетов', exact: true }).click();
    await listCaptured;
    await adminPage.getByText(title, { exact: true }).click();
    let detail = adminPage.getByRole('dialog');
    async function move(status) {
      await detail.getByLabel('Этап', { exact: true }).selectOption(status);
      response = adminPage.waitForResponse(r => r.url().endsWith('/development/tickets') && r.request().method() === 'PUT');
      await detail.getByRole('button', { name: /Сохранить/ }).click();
      assert.equal((await response).status(), 200);
    }
    await move('clarifying');
    releaseList();
    await adminPage.waitForResponse(r => r.url().includes('/api/v1/development?') && r.request().method() === 'GET');
    await adminPage.locator('.development-column.stage-clarifying').getByText(title, { exact: true }).waitFor();
    await move('ready');
    const beforeTransfer = await request('GET', `/development/tickets/${ticket.id}?responsibilityScopeId=${ids.scope}`, undefined, admin.accessToken);
    const b = beforeTransfer.body.ticket;
    const parallel = await request('PUT', '/development/tickets', { id:b.id,responsibilityScopeId:ids.scope,title:b.title,description:b.description+' Уточнение коллеги.',section:b.section,status:b.status,version:b.version }, admin.accessToken);
    assert.equal(parallel.status, 200);
    response = adminPage.waitForResponse(r => r.url().endsWith('/development/tickets') && r.request().method() === 'PUT');
    await detail.getByRole('button', { name:'В продакшен',exact:true }).click();
    assert.equal((await response).status(),409);
    const merge = detail.getByRole('button', { name:'Сохранить мои правки в актуальную версию',exact:true });
    await merge.waitFor();
    response = adminPage.waitForResponse(r => r.url().endsWith('/development/tickets') && r.request().method() === 'PUT');
    await merge.click();
    const transferred = await response;
    assert.equal(transferred.status(),200);
    const transfer = await transferred.json();
    assert.equal(transfer.status,'in_progress','Quick transfer intent survives conflict');
    assert.ok(transfer.description.endsWith('Уточнение коллеги.'),'Untouched latest fields survive conflict merge');
    console.log('PASS stale board read ignored and quick production transfer survives a conflict');
    await move('review');
    await move('done');
    const saved = await request('GET', `/development/tickets/${ticket.id}?responsibilityScopeId=${ids.scope}`, undefined, admin.accessToken);
    assert.equal(saved.status, 200);
    assert.equal(saved.body.ticket.status, 'done');
    assert.equal(saved.body.ticket.number, ticket.number);
    assert.ok(saved.body.events.some(event => event.text === 'Повторяется после повторного входа.'));
    assert.equal(saved.body.events.filter(event => event.type === 'status').length, 5);
    console.log('PASS administrator completes both funnels with one ticket and preserved history');

    // Concurrent change: the browser keeps the user's text on HTTP 409.
    await detail.getByLabel('Описание', { exact: true }).fill('Черновик автора проверки — не терять');
    const current = saved.body.ticket;
    const update = await request('PUT', '/development/tickets', { id: current.id, responsibilityScopeId: ids.scope, title: current.title, description: current.description, section: current.section, status: 'review', version: current.version }, admin.accessToken);
    assert.equal(update.status, 200);
    response = adminPage.waitForResponse(r => r.url().endsWith('/development/tickets') && r.request().method() === 'PUT');
    await detail.getByRole('button', { name: /Сохранить/ }).click();
    assert.equal((await response).status(), 409);
    assert.equal(await detail.getByLabel('Описание', { exact: true }).inputValue(), 'Черновик автора проверки — не терять');
    console.log('PASS concurrent update does not overwrite the server or discard the draft');
    adminPage.on('dialog', d => d.accept());
    await adminPage.reload();
    await adminPage.getByRole('button', { name: /Продакшен/ }).click();
    await adminPage.getByText(title, { exact: true }).waitFor();
    const out = path.resolve(__dirname, '../.local/development-browser-qa' + (process.env.DEVELOPMENT_BUILT_FRONTEND === 'true' ? '-built' : ''));
    await fs.mkdir(out, { recursive: true });
    await adminPage.screenshot({ path: path.join(out, 'production-desktop.png'), fullPage: true });
    await adminPage.setViewportSize({ width: 390, height: 844 });
    assert.ok(await adminPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile board must fit viewport');
    await adminPage.getByText(title, { exact: true }).click();
    await adminPage.getByRole('dialog').getByLabel('Название',{exact:true}).waitFor();
    const overlay = await adminPage.locator('.development-overlay').boundingBox();
    assert.ok(overlay.y >= -1 && overlay.y <= 1 && overlay.height <= 845, 'Dialog overlay covers the viewport');
    await adminPage.screenshot({ path: path.join(out, 'ticket-mobile.png') });
    assert.ok(await adminPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile dialog must fit viewport');
    console.log('PASS responsive desktop board and mobile ticket');
    const mobileDialog = adminPage.getByRole('dialog');
    await mobileDialog.getByLabel('Описание',{exact:true}).fill('Мой черновик до комментария');
    const beforeComment = (await request('GET', `/development/tickets/${ticket.id}?responsibilityScopeId=${ids.scope}`,undefined,admin.accessToken)).body.ticket;
    assert.equal((await request('PUT','/development/tickets',{id:beforeComment.id,responsibilityScopeId:ids.scope,title:beforeComment.title,description:'Параллельная правка коллеги',section:beforeComment.section,status:beforeComment.status,version:beforeComment.version},admin.accessToken)).status,200);
    await mobileDialog.getByLabel('Комментарий',{exact:true}).fill('Уточнение с открытым черновиком');
    response=adminPage.waitForResponse(r=>r.url().endsWith('/development/comments')&&r.request().method()==='POST');
    await mobileDialog.getByRole('button',{name:'Добавить комментарий',exact:true}).click();
    assert.equal((await response).status(),201);
    await mobileDialog.getByRole('region',{name:'Конфликт изменений',exact:true}).waitFor();
    assert.equal(await mobileDialog.getByLabel('Описание',{exact:true}).inputValue(),'Мой черновик до комментария');
    assert.equal(await mobileDialog.getByRole('button',{name:'Сохранить',exact:true}).isDisabled(),true);
    console.log('PASS comment refresh preserves draft and exposes concurrent field conflict');
    await fixture.restartApi();
    const persisted = await request('GET', `/development/tickets/${ticket.id}?responsibilityScopeId=${ids.scope}`, undefined, employee.accessToken);
    assert.equal(persisted.status, 200);
    assert.equal(persisted.body.ticket.status, 'review');
    // Real remembered-device renewal while submitting a draft must keep the dialog and result.
    const issued = await request('POST', `/access/users/${ids.drivers[1]}/password`, { phone:'+79990008644' }, admin.accessToken);
    assert.equal(issued.status,201);
    const rememberedContext = await browser.newContext({viewport:{width:1440,height:1000}});
    const remembered = await rememberedContext.newPage();
    remembered.setDefaultTimeout(15000);
    remembered.on('pageerror',e=>errors.push(e.message));
    await remembered.goto(fixture.origin+'/?section=development');
    await remembered.locator('#login-phone').fill(issued.body.phone);
    await remembered.locator('#login-password').fill(issued.body.password);
    const passwordResponse = remembered.waitForResponse(r=>r.url().endsWith('/auth/password'));
    await remembered.getByRole('button',{name:'Войти',exact:true}).click();
    const signedIn = await (await passwordResponse).json();
    await remembered.getByRole('button',{name:/Новый тикет/}).click();
    const renewalDialog=remembered.getByRole('dialog');
    await renewalDialog.getByLabel('Название',{exact:true}).fill('Тикет после продления сессии');
    await renewalDialog.getByLabel('Описание',{exact:true}).fill('Этот введённый текст должен сохраниться при автоматическом продлении входа.');
    await fixture.adminPool.query("UPDATE sessions SET expires_at=now()-interval '1 second' WHERE id=$1",[signedIn.actor.sessionId]);
    const renewed = remembered.waitForResponse(r=>r.url().endsWith('/auth/refresh')&&r.status()===200);
    const committed = remembered.waitForResponse(r=>r.url().endsWith('/development/tickets')&&r.status()===200);
    await renewalDialog.getByRole('button',{name:'Создать тикет',exact:true}).click();
    await renewed;
    await committed;
    await renewalDialog.getByRole('heading',{name:/Тикет №/}).waitFor();
    assert.equal(await renewalDialog.getByLabel('Название',{exact:true}).inputValue(),'Тикет после продления сессии');
    assert.equal(await renewalDialog.getByRole('button',{name:'Сохранить',exact:true}).isDisabled(),true);
    console.log('PASS remembered-device token renewal keeps draft and committed result visible');
    assert.deepEqual(errors, []);
    console.log('PASS API restart preserves ticket, comments and session; no JavaScript errors');
  } finally {
    if (browser) await browser.close();
    await fixture.close();
  }
})().catch(error => { console.error(error); process.exit(1); });
