'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, createHash } = require('node:crypto');
require('../recovered/node_modules/reflect-metadata');
const { createTestServer } = require('./local-test-server.cjs');
const { DatabaseService } = require('../recovered/apps/api/src/platform/database.service');
const { IdentityRepository } = require('../recovered/apps/api/src/modules/identity-access/infrastructure/identity.repository');
const { NeuralService } = require('../recovered/apps/api/src/modules/neural/neural.service');
const hashToken = token => createHash('sha256').update(token).digest('hex');

test('neural configuration, access isolation and independent accounting survive transaction rollback', { timeout: 180000 }, async t => {
  const fixture = await createTestServer(), { ids, request, adminPool: db } = fixture;
  const applicationDb = new DatabaseService({ value: { databaseUrl: process.env.DATABASE_URL } });
  const originalFetch = global.fetch, originalKey = process.env.OPENAI_API_KEY;
  t.after(async () => { global.fetch = originalFetch; if (originalKey === undefined) delete process.env.OPENAI_API_KEY; else process.env.OPENAI_API_KEY = originalKey; await applicationDb.onApplicationShutdown(); await fixture.close(); });
  const service = new NeuralService(applicationDb), identity = new IdentityRepository(applicationDb), admin = await fixture.devLogin(ids.admin), dispatcher = await fixture.devLogin(ids.dispatcher);
  const actor = await identity.actorByToken(hashToken(admin.accessToken));
  const scope = { legalEntityId: ids.legal, regionId: ids.region, projectId: ids.project, responsibilityScopeId: ids.scope };
  const query = `?responsibilityScopeId=${ids.scope}`;
  const initial = await request('GET', `/neural/settings${query}`, undefined, admin.accessToken);
  assert.equal(initial.status, 200); assert.equal(initial.body.providers.length, 5); assert.equal(initial.body.tasks.conversation_summary, null);
  for (const path of ['settings', 'usage']) assert.equal((await request('GET', `/neural/${path}${query}`, undefined, dispatcher.accessToken)).status, 403);
  const otherScope = randomUUID();
  await db.query('INSERT INTO responsibility_scopes(id,project_id,name) VALUES($1,$2,$3)', [otherScope, ids.project, 'Unassigned scope']);
  assert.equal((await request('GET', `/neural/settings?responsibilityScopeId=${otherScope}`, undefined, admin.accessToken)).status, 403);
  let calls = 0;
  global.fetch = async (url, options) => {
    if (!String(url).startsWith('https://api.openai.com/')) return originalFetch(url, options);
    calls++; assert.equal(options.headers.authorization, 'Bearer synthetic-test-key');
    return new Response(JSON.stringify({ choices: [{ message: { content: 'Synthetic answer' }, finish_reason: 'stop' }], usage: { prompt_tokens: 1000, completion_tokens: 100 } }));
  };
  process.env.OPENAI_API_KEY = 'synthetic-test-key';
  const run = client => service.run(client, actor, scope, { task: 'conversation_summary', system: 'Test system', prompt: 'Synthetic data', metadata: { summaryId: randomUUID(), privateText: 'never persist' } });
  assert.equal(await applicationDb.transaction(run), null); assert.equal(calls, 0);
  const config = { responsibilityScopeId: ids.scope, profiles: [{ id: 'main', name: 'Test model', provider: 'openai', model: 'test-model', enabled: true, inputPricePerMillion: 2, outputPricePerMillion: 8, currency: 'USD', maxOutputTokens: 4096 }], tasks: { conversation_summary: 'main', work_order_prices: null } };
  assert.equal((await request('PUT', `/neural/settings${query}`, config, dispatcher.accessToken)).status, 403);
  assert.equal((await request('PUT', `/neural/settings?responsibilityScopeId=${otherScope}`, config, admin.accessToken)).status, 400);
  const saved = await request('PUT', `/neural/settings${query}`, config, admin.accessToken);
  assert.equal(saved.status, 200); assert.ok(!JSON.stringify(saved.body).includes('synthetic-test-key'));
  let usageId;
  await assert.rejects(applicationDb.transaction(async client => { const result = await run(client); usageId = result.usageId; assert.equal(result.cost, 0.0028); throw new Error('Caller rollback'); }), /Caller rollback/);
  const ledger = (await db.query('SELECT status,cost,metadata FROM neural_usage WHERE id=$1', [usageId])).rows[0];
  assert.equal(ledger.status, 'success'); assert.equal(Number(ledger.cost), 0.0028); assert.equal(ledger.metadata.privateText, undefined);
  global.fetch = async (url, options) => String(url).startsWith('https://api.openai.com/') ? new Response(JSON.stringify({ error: 'secret-do-not-expose' }), { status: 429 }) : originalFetch(url, options);
  await assert.rejects(applicationDb.transaction(run), error => error.getStatus() === 502 && !JSON.stringify(error.getResponse()).includes('secret'));
  const report = await request('GET', `/neural/usage${query}`, undefined, admin.accessToken);
  assert.equal(report.status, 200); assert.equal(report.body.totals.calls, 2); assert.equal(report.body.totals.successful, 1); assert.equal(report.body.totals.failed, 1);
  assert.equal(report.body.totals.inputTokens, 1000); assert.equal(report.body.totals.outputTokens, 100); assert.equal(report.body.totals.unpricedCalls, 1);
  assert.deepEqual(report.body.totals.costs, [{ currency: 'USD', amount: 0.0028 }]);
  assert.equal(report.body.records.find(row => row.status === 'failed').errorCode, 'HTTP_429');
  assert.equal((await request('GET', `/neural/usage?responsibilityScopeId=${otherScope}`, undefined, admin.accessToken)).status, 403);
  // This real summary request acquires the application's user/scope locks. Its
  // independent ledger INSERT must remain compatible with the user's FK lock.
  delete process.env.OPENAI_API_KEY;
  const channelId = randomUUID();
  assert.equal((await request('POST', '/team/conversations', { id: channelId, responsibilityScopeId: ids.scope, kind: 'channel', title: 'Synthetic neural test', memberIds: [] }, admin.accessToken)).status, 201);
  assert.equal((await request('POST', '/team/messages', { id: randomUUID(), responsibilityScopeId: ids.scope, conversationId: channelId, text: 'Задача: проверить синтетический заказ.', parentId: null }, admin.accessToken)).status, 201);
  const missingKey = await request('POST', '/team/summaries', { responsibilityScopeId: ids.scope, periodStart: new Date(Date.now() - 60000).toISOString(), periodEnd: new Date(Date.now() + 1000).toISOString() }, admin.accessToken);
  assert.equal(missingKey.status, 502, JSON.stringify(missingKey.body));
  assert.equal(missingKey.body.code, 'NEURAL_PROVIDER_ERROR'); assert.match(missingKey.body.message, /API-ключ/);
  const missingLedger = (await db.query("SELECT status,cost,input_tokens FROM neural_usage WHERE error_code='KEY_NOT_CONFIGURED'")).rows;
  assert.equal(missingLedger.length, 1); assert.equal(missingLedger[0].status, 'failed'); assert.equal(missingLedger[0].cost, null); assert.equal(missingLedger[0].input_tokens, null);
  assert.equal((await db.query('SELECT count(*) AS count FROM team_summaries')).rows[0].count, '0');
  const disabled = { ...config, profiles: [{ ...config.profiles[0], enabled: false }] };
  assert.equal((await request('PUT', `/neural/settings${query}`, disabled, admin.accessToken)).status, 200);
  assert.equal(await applicationDb.transaction(run), null);
  await db.query('DELETE FROM access_grants WHERE user_id=$1 AND responsibility_scope_id=$2', [ids.admin, ids.scope]);
  assert.equal((await request('GET', `/neural/settings${query}`, undefined, admin.accessToken)).status, 403);
});
