'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {createTestServer}=require('./local-test-server.cjs');

test('recruiter worklist, contacts, security and confirmed starts preserve permissions and event meaning',{timeout:180000},async t=>{
  const f=await createTestServer();t.after(()=>f.close());
  const {request,devLogin,adminPool:db,ids}=f;
  const tuple=[ids.legal,ids.region,ids.project,ids.scope];
  async function person(role){const id=randomUUID();await db.query('INSERT INTO users(id,display_name,role,active,approved) VALUES($1,$2,$3,true,true)',[id,`Synthetic ${role}`,role]);await db.query('INSERT INTO access_grants(user_id,legal_entity_id,region_id,project_id,responsibility_scope_id,personal_data_visible) VALUES($1,$2,$3,$4,$5,true)',[id,...tuple]);return {id,...await devLogin(id)};}
  const recruiter=await person('recruiter'),manager=await person('manager'),other=await person('dispatcher'),external=await person('external_recruiter');
  const expect=(result,status=200)=>{assert.equal(result.status,status,JSON.stringify(result.body));return result.body;};
  const get=(route,who=recruiter)=>request('GET',`/recruitment/${route}${route.includes('?')?'&':'?'}responsibilityScopeId=${ids.scope}`,undefined,who.accessToken);
  const put=(type,body,who=recruiter)=>request('PUT',`/recruitment/${type}`,body,who.accessToken);
  const post=(type,body,who=recruiter)=>request('POST',`/recruitment/${type}`,{responsibilityScopeId:ids.scope,...body},who.accessToken);
  const seed=(patch={})=>({id:randomUUID(),version:0,responsibilityScopeId:ids.scope,recruiterId:recruiter.id,...patch});
  const demand=expect(await put('requests',seed({title:'Synthetic need',city:'Москва',kind:'driver',quantity:3,priority:'normal',status:'open',requiresSecurity:true})));
  const secondDemand=expect(await put('requests',seed({title:'Other synthetic need',city:'Москва',kind:'driver',quantity:1,priority:'normal',status:'open'})));
  const candidate=expect(await put('candidates',seed({fullName:'Synthetic Person',phone:'+79992223344',city:'Москва',kind:'driver',source:'avito'})));
  let app=expect(await put('applications',seed({candidateId:candidate.id,requestId:demand.id,stage:'qualified'})));
  let firstTask;
  const future=new Date(Date.now()+86400000).toISOString();
  await t.test('worklist has accurate filtered counts and candidate detail without full snapshot',async()=>{
    const list=expect(await get('worklist?view=all&page=1&pageSize=1&recruiterId='+recruiter.id));
    assert.equal(list.total,1);assert.equal(list.items.length,1);assert.equal(list.items[0].candidate.id,candidate.id);
    assert.equal(list.counts.no_next,1);assert.equal(list.permissions.securityDecision,false);
    assert.ok(list.workflowOperators.some(p=>p.id===manager.id));assert.ok(!list.workflowOperators.some(p=>p.id===recruiter.id));
    const detail=expect(await get(`candidate?candidateId=${candidate.id}`));assert.equal(detail.applications[0].id,app.id);assert.equal(detail.contactTotal,0);
    expect(await get('worklist?pageSize=1000'),400);
    assert.equal(expect(await get('worklist?search=no-such-person')).total,0);
    assert.equal(Number((await db.query("SELECT count(*) FROM recruitment_activity WHERE actor_id=$1 AND kind='data_read'",[recruiter.id])).rows[0].count),1);
  });
  await t.test('contact and next task commit together; exact retries do not duplicate; inquiry preserves first source',async()=>{
    const body={id:randomUUID(),candidateId:candidate.id,applicationId:app.id,result:'no_answer',notes:'SYNTHETIC PRIVATE NOTE',nextAction:{title:'Перезвонить',dueAt:future,assigneeId:recruiter.id}};
    expect(await post('contacts',{...body,nextAction:null}),400);
    expect(await post('contacts',{...body,nextAction:{...body.nextAction,dueAt:new Date(Date.now()-60000).toISOString()}}),400);
    assert.equal(Number((await db.query('SELECT count(*) FROM recruitment_contacts')).rows[0].count),0);
    const [a,b]=await Promise.all([post('contacts',body),post('contacts',body)]);
    const saved=expect(a,201);expect(b,201);firstTask=saved.task;
    assert.equal(firstTask.applicationId,app.id);assert.equal(firstTask.id,saved.contact.id);
    assert.equal(Number((await db.query('SELECT count(*) FROM recruitment_contacts')).rows[0].count),1);
    expect(await post('contacts',{...body,notes:'changed'}),409);
    assert.equal(expect(await get('worklist?view=new')).total,0);
    expect(await post('contacts',{id:randomUUID(),candidateId:candidate.id,applicationId:app.id,result:'inquiry',source:'ati'}),201);
    assert.equal(expect(await get('worklist?view=new')).total,1);
    let detail=expect(await get(`candidate?candidateId=${candidate.id}`));assert.equal(detail.contactTotal,2);assert.equal(detail.candidate.source,'avito');
    assert.equal(expect(await get('worklist?source=ati')).total,1);assert.equal(expect(await get('worklist?view=no_next')).total,0);
    expect(await post('contacts',{id:randomUUID(),candidateId:candidate.id,applicationId:app.id,result:'connected',completeTaskId:firstTask.id}),201);
    assert.equal(expect(await get('worklist?view=new')).total,0);
    detail=expect(await get(`candidate?candidateId=${candidate.id}`));assert.equal(detail.tasks[0].status,'done');
    assert.equal(expect(await get('worklist?view=no_next')).total,1);
    const invalidApp=expect(await put('applications',seed({candidateId:candidate.id,requestId:secondDemand.id,stage:'new'})));
    expect(await post('contacts',{id:randomUUID(),candidateId:candidate.id,applicationId:invalidApp.id,result:'connected',completeTaskId:firstTask.id,nextAction:{title:'Must roll back',dueAt:future,assigneeId:recruiter.id}}),400);
    assert.equal(Number((await db.query("SELECT count(*) FROM recruitment_tasks WHERE title='Must roll back'")).rows[0].count),0);
  });
  await t.test('required security cannot be forged by generic updates; decisions and tasks have a durable audit',async()=>{
    expect(await put('requests',{...demand,requiresSecurity:false}),403);
    expect(await put('applications',{...app,stage:'internship',securityStatus:'approved'}),400);
    expect(await post('security',{applicationId:app.id,version:app.version,status:'approved'}),403);
    expect(await post('security',{applicationId:app.id,version:app.version,status:'submitted',dueAt:future}),400);
    app=expect(await post('security',{applicationId:app.id,version:app.version,status:'documents',assigneeId:manager.id,dueAt:future},manager),201);
    app=expect(await post('security',{applicationId:app.id,version:app.version,status:'submitted',dueAt:future}),201);
    assert.equal(app.securityStatus,'submitted');
    assert.equal(expect(await get('worklist?view=security')).total,1);
    app=expect(await post('security',{applicationId:app.id,version:app.version,status:'in_review',assigneeId:manager.id,dueAt:future},manager),201);
    const task=(await db.query("SELECT * FROM recruitment_tasks WHERE workflow_kind='security' AND status='open'")).rows[0];
    assert.equal(task.assignee_id,manager.id);
    const publicTask=expect(await get(`candidate?candidateId=${candidate.id}`,manager)).tasks.find(t=>t.id===task.id);
    assert.equal(publicTask.workflowKind,'security');
    expect(await put('tasks',{...publicTask,status:'done'},manager),400);
    expect(await post('contacts',{id:randomUUID(),candidateId:candidate.id,applicationId:app.id,result:'connected',completeTaskId:task.id},manager),400);
    app=expect(await post('security',{applicationId:app.id,version:app.version,status:'documents',dueAt:null}),201);
    assert.equal(app.securityDueAt,future);
    assert.equal((await db.query('SELECT status FROM recruitment_tasks WHERE id=$1',[task.id])).rows[0].status,'open');
    expect(await post('security',{applicationId:app.id,version:app.version,status:'not_requested'},manager),400);
    assert.equal(expect(await get('worklist?view=no_next&recruiterId='+recruiter.id)).total,1);
    assert.equal(expect(await get('worklist?view=no_next&recruiterId='+manager.id,manager)).total,0);
    expect(await post('security',{applicationId:app.id,version:app.version,status:'approved'},other),403);
    const stale={...app};
    app=expect(await post('security',{applicationId:app.id,version:app.version,status:'approved',note:'SYNTHETIC SECURITY PRIVATE'},manager),201);
    expect(await post('security',{applicationId:app.id,version:stale.version,status:'approved'},manager),409);
    const recruiterDetail=expect(await get(`candidate?candidateId=${candidate.id}`));
    assert.ok(!JSON.stringify(recruiterDetail).includes('SYNTHETIC SECURITY PRIVATE'));
    assert.ok(JSON.stringify(expect(await get(`candidate?candidateId=${candidate.id}`,manager))).includes('SYNTHETIC SECURITY PRIVATE'));
    assert.equal(Number((await db.query("SELECT count(*) FROM recruitment_tasks WHERE workflow_kind='security' AND status='open'")).rows[0].count),0);
    app=expect(await put('applications',{...app,stage:'internship'}));
    app=expect(await put('applications',{...app,stage:'hired',startDate:'2026-01-01',confirmedStartDate:'2026-01-01',attendanceStatus:'confirmed'}));
    assert.equal(app.attendanceStatus,'unconfirmed');assert.equal(app.confirmedStartDate,null);
  });
  await t.test('a manual hire becomes confirmed only by an operational employee; corrections retain history',async()=>{
    expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'confirmed',date:'2026-01-01'}),403);
    expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'confirmed',date:'2099-01-01'},manager),400);
    app=expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'confirmed',date:'2026-01-01'},manager),201);
    assert.equal(app.confirmedStartDate,'2026-01-01');assert.equal(app.confirmedBy,manager.id);
    expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'no_show'},manager),400);
    app=expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'no_show',note:'Synthetic correction'},manager),201);
    assert.equal(app.confirmedStartDate,null);assert.equal(app.attendanceStatus,'no_show');
    const events=expect(await get(`candidate?candidateId=${candidate.id}`,manager)).workflowEvents.filter(e=>e.kind==='start');assert.equal(events.length,2);
    app=expect(await put('applications',{...app,startDate:'2099-01-01'}));
    expect(await post('start-confirmation',{applicationId:app.id,version:app.version,status:'no_show',note:'Too soon'},manager),400);
  });
  await t.test('external visibility follows exact request revocations including linked contacts and tasks',async()=>{
    await db.query(`INSERT INTO recruitment_external_access(legal_entity_id,region_id,project_id,responsibility_scope_id,user_id,request_ids,status,updated_by) VALUES($1,$2,$3,$4,$5,$6,'active',$7)`,[...tuple,external.id,[demand.id,secondDemand.id],manager.id]);
    const ec=expect(await put('candidates',seed({recruiterId:external.id,fullName:'External own',phone:'+79992223355',city:'Москва',kind:'driver',source:'ati'}),external));
    const ea=expect(await put('applications',seed({recruiterId:external.id,candidateId:ec.id,requestId:demand.id,stage:'new'}),external));
    const ea2=expect(await put('applications',seed({recruiterId:external.id,candidateId:ec.id,requestId:secondDemand.id,stage:'qualified'}),external));
    const unrelatedTask=expect(await put('tasks',seed({candidateId:candidate.id,title:'Private unrelated task',dueAt:future,assigneeId:manager.id,status:'done',notes:'Must never leak'}),manager));
    const collisionBody={id:unrelatedTask.id,candidateId:ec.id,applicationId:ea.id,result:'connected'};
    assert.equal(expect(await post('contacts',collisionBody,external),201).task,null);
    assert.equal(expect(await post('contacts',collisionBody,external),201).task,null);
    expect(await post('contacts',{id:randomUUID(),candidateId:ec.id,applicationId:ea2.id,result:'connected'},external),201);
    expect(await post('contacts',{id:randomUUID(),candidateId:ec.id,applicationId:ea2.id,result:'inquiry',source:'ati'},external),201);
    const revokedTask=expect(await post('contacts',{id:randomUUID(),candidateId:ec.id,applicationId:ea.id,result:'callback',notes:'Withdrawn-request-only-note',nextAction:{title:'Withdrawn-request-task',dueAt:future,assigneeId:external.id}},external),201).task;
    assert.equal(expect(await get('worklist?view=all',external)).total,1);
    expect(await get(`candidate?candidateId=${candidate.id}`,external),403);
    expect(await post('contacts',{id:randomUUID(),candidateId:candidate.id,result:'connected'},external),403);
    expect(await post('security',{applicationId:ea.id,version:ea.version,status:'approved'},external),403);
    await db.query('UPDATE recruitment_external_access SET request_ids=$2 WHERE user_id=$1',[external.id,[secondDemand.id]]);
    const detail=expect(await get(`candidate?candidateId=${ec.id}`,external));
    assert.equal(detail.applications.length,1);assert.equal(detail.contacts.length,2);assert.equal(detail.tasks.length,0);
    const list=expect(await get('worklist?view=all',external));assert.equal(list.items[0].lastContact.applicationId,ea2.id);assert.equal(list.items[0].tasks.length,0);
    assert.equal(expect(await get('worklist?view=new',external)).total,1);
    expect(await put('tasks',{...revokedTask,applicationId:null},external),403);
    const snapshot=expect(await request('GET',`/recruitment?responsibilityScopeId=${ids.scope}`,undefined,external.accessToken));
    assert.ok(!JSON.stringify(snapshot).includes('Withdrawn-request-task'));
    const reminders=expect(await get('reminders',external));
    assert.ok(!JSON.stringify(reminders).includes('Withdrawn-request-task'));
    expect(await post('contacts',{id:randomUUID(),candidateId:ec.id,applicationId:ea.id,result:'connected'},external),403);
    await db.query("UPDATE recruitment_external_access SET status='revoked' WHERE user_id=$1",[external.id]);
    expect(await get('worklist',external),403);expect(await get(`candidate?candidateId=${ec.id}`,external),403);
  });
  await t.test('worklist is genuinely paginated above the old snapshot cap, with stable page boundaries',async()=>{
    await db.query(`INSERT INTO recruitment_candidates(id,legal_entity_id,region_id,project_id,responsibility_scope_id,full_name,phone,city,kind,recruiter_id,source,created_by,updated_by)
      SELECT gen_random_uuid(),$1,$2,$3,$4,'Synthetic load '||n,'+7888'||lpad(n::text,7,'0'),'Москва','driver',$5,'avito',$5,$5 FROM generate_series(1,10005) n`,[...tuple,recruiter.id]);
    const a=expect(await get('worklist?page=1&pageSize=25')),b=expect(await get('worklist?page=2&pageSize=25'));
    assert.equal(a.total,10007);assert.equal(a.items.length,25);assert.equal(b.items.length,25);
    assert.equal(new Set([...a.items,...b.items].map(r=>r.candidate.id)).size,50);
    assert.equal(expect(await get('worklist?search=Synthetic%20Person')).total,1);
    expect(await request('GET',`/recruitment?responsibilityScopeId=${ids.scope}`,undefined,recruiter.accessToken),400);
    const serialized=JSON.stringify((await db.query("SELECT payload FROM audit_events WHERE payload->>'action' LIKE 'recruitment.%'")).rows);
    assert.ok(!serialized.includes('SYNTHETIC PRIVATE NOTE'));assert.ok(!serialized.includes('SYNTHETIC SECURITY PRIVATE'));
    await db.query('UPDATE access_grants SET personal_data_visible=false WHERE user_id=$1',[recruiter.id]);
    expect(await get('worklist'),403);expect(await get(`candidate?candidateId=${candidate.id}`),403);
  });
});
