'use strict';
// End-to-end scenarios use a disposable PostgreSQL and synthetic people only.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { createTestServer } = require('./local-test-server.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const fixture = await createTestServer({ builtFrontend: process.env.RECRUITMENT_BUILT_FRONTEND === 'true' });
  const out = path.resolve(__dirname, '../.local/recruitment-browser-qa');
  let browser;
  try {
    await fs.mkdir(out, { recursive: true });
    await fixture.adminPool.query('UPDATE access_grants SET personal_data_visible=true WHERE user_id=ANY($1::uuid[])', [[fixture.ids.admin, fixture.ids.dispatcher]]);
    await fixture.adminPool.query("UPDATE users SET role='manager',display_name='Рекрутер тестового проекта' WHERE id=$1", [fixture.ids.dispatcher]);
    const administrator = await fixture.devLogin(fixture.ids.admin);
    const phone = '+79990000991';
    const issued = await fixture.request('POST', `/access/users/${fixture.ids.dispatcher}/password`, { phone }, administrator.accessToken);
    assert.equal(issued.status, 201);
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, timezoneId: 'Europe/Moscow' });
    const page = await context.newPage();
    page.setDefaultTimeout(15000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    let acceptLeave = true;
    let dialogCount = 0;
    page.on('dialog', dialog => { dialogCount += 1; return acceptLeave ? dialog.accept() : dialog.dismiss(); });
    await page.goto(fixture.origin);
    await page.locator('#login-phone').fill(phone);
    await page.locator('#login-password').fill(issued.body.password);
    const loginResponse = page.waitForResponse(response => response.url().endsWith('/auth/password') && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Войти', exact: true }).click();
    const session = await (await loginResponse).json();
    assert.ok(session.accessToken);
    await page.getByRole('button', { name: 'Рекрутинг', exact: true }).click();
    await page.getByRole('heading', { name: 'Рекрутинг', exact: true }).waitFor();

    const tabs = page.getByRole('navigation', { name: 'Разделы рекрутинга' });
    const form = () => page.getByRole('dialog');
    const save = async (collection, expected = 200) => {
      const pending = page.waitForResponse(response => response.url().endsWith(`/recruitment/${collection}`) && response.request().method() === 'PUT');
      await form().getByRole('button', { name: 'Сохранить', exact: true }).click();
      const response = await pending;
      const body = await response.json();
      assert.equal(response.status(), expected, JSON.stringify(body));
      if (expected === 200) await page.getByText('Сохранено', { exact: true }).waitFor();
      return body;
    };
    const localMinute = async (offset = 0) => page.evaluate((offset) => {
      const date = new Date(Date.now() + offset);
      return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
    }, offset);
    const snapshot = async () => (await fixture.request('GET', `/recruitment?responsibilityScopeId=${fixture.ids.scope}`, undefined, session.accessToken)).body;

    await tabs.getByRole('button', { name: 'Потребности', exact: true }).click();
    await page.getByRole('button', { name: 'Создать потребность', exact: true }).first().click();
    await form().getByLabel('Название потребности', { exact: true }).fill('Утренний маршрут · тест');
    await form().getByLabel('Город', { exact: true }).fill('Москва');
    await form().getByLabel('Нужно водителей', { exact: true }).fill('3');
    await form().getByLabel('График работы', { exact: true }).fill('5/2, с 06:00');
    await form().getByLabel('Условия оплаты', { exact: true }).fill('Синтетические условия за смену');
    await form().getByLabel('Ссылка на вакансию hh', { exact: true }).fill('https://hh.ru/vacancy/123456');
    let demand = await save('requests');

    await tabs.getByRole('button', { name: 'Кандидаты', exact: true }).click();
    await page.getByRole('button', { name: 'Список', exact: true }).click();
    await page.getByRole('button', { name: 'Добавить кандидата', exact: true }).first().click();
    await form().getByLabel('ФИО', { exact: true }).fill('Тестовый Алексей Водитель');
    await form().getByLabel('Телефон', { exact: true }).fill('8 (999) 123-45-67');
    await form().getByLabel('Город', { exact: true }).fill('Москва');
    await form().getByLabel('Район проживания', { exact: true }).fill('Северный');
    await form().getByLabel('Категории прав', { exact: true }).fill('B, C');
    await form().getByLabel('Ссылка на кандидата или диалог hh', { exact: true }).fill('https://hh.ru/resume/synthetic-recruitment');
    const candidate = await save('candidates');
    assert.equal(candidate.phone, '+79991234567');
    await form().getByRole('heading', { name: candidate.fullName, exact: true }).waitFor();
    const hh = form().getByRole('link', { name: 'Перейти на hh ↗', exact: true });
    assert.equal(await hh.getAttribute('href'), candidate.hhUrl);
    assert.equal(await hh.getAttribute('target'), '_blank');
    assert.match(await hh.getAttribute('rel'), /noopener/);

    await form().getByRole('button', { name: 'Добавить в подбор', exact: true }).click();
    await form().getByLabel('Потребность', { exact: true }).selectOption(demand.id);
    await form().getByLabel('Этап подбора', { exact: true }).selectOption('interview');
    let application = await save('applications');
    await form().getByRole('button', { name: 'Напомнить о кандидате', exact: true }).click();
    await form().getByLabel('Название задачи', { exact: true }).fill('Узнать решение по утреннему маршруту');
    await form().getByLabel('Дата и время напоминания', { exact: true }).fill(await localMinute(-120000));
    const task = await save('tasks');
    await page.getByText('Напоминания по подбору: 1', { exact: true }).waitFor();
    await form().getByRole('button', { name: 'Закрыть карточку', exact: true }).click();
    await page.getByRole('button', { name: 'Планирование', exact: true }).click();
    await page.getByRole('heading', { name: 'Планирование', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Открыть задачи', exact: true }).click();
    await page.getByRole('heading', { name: task.title, exact: true }).waitFor();
    await page.getByRole('button', { name: 'Выполнить', exact: true }).click();
    await page.getByText('Задача выполнена', { exact: true }).waitFor();
    await page.locator('.recruitment-reminder').waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: 'Выполненные', exact: true }).click();
    await page.getByRole('heading', { name: task.title, exact: true }).waitFor();
    assert.equal((await snapshot()).tasks[0].status, 'done');
    console.log('PASS request, candidate, hh handoff, interview and durable cross-section reminder completion');

    await tabs.getByRole('button', { name: 'Кандидаты', exact: true }).click();
    await page.getByRole('button', { name: 'Список', exact: true }).click();
    await page.getByRole('button', { name: 'Добавить кандидата', exact: true }).first().click();
    await form().getByLabel('ФИО', { exact: true }).fill('Тестовый Перевозчик');
    await form().getByLabel('Телефон', { exact: true }).fill('+79997654321');
    await form().getByLabel('Город', { exact: true }).fill('Тула');
    await form().getByLabel('Направление', { exact: true }).selectOption('carrier');
    await form().getByLabel('Тип кузова / автомобиль', { exact: true }).fill('Фургон');
    await form().getByLabel('Габариты кузова', { exact: true }).fill('4 × 2 × 2 м');
    await form().getByLabel('Грузоподъёмность / объём', { exact: true }).fill('1,5 т / 12 м³');
    const carrier = await save('candidates');
    await form().getByText('4 × 2 × 2 м · 1,5 т / 12 м³', { exact: true }).waitFor();
    await form().getByRole('button', { name: 'Закрыть карточку', exact: true }).click();
    await page.getByLabel('Город кандидата', { exact: true }).selectOption('Тула');
    await page.waitForFunction(() => !document.querySelector('.recruitment-loading') && document.querySelectorAll('.recruitment-worklist tbody tr').length === 1);
    assert.equal(await page.locator('.recruitment-worklist tbody tr').count(), 1);
    await page.getByRole('button', { name: carrier.fullName, exact: true }).waitFor();
    await page.getByLabel('Город кандидата', { exact: true }).selectOption('');
    await page.getByLabel('Направление', { exact: true }).selectOption('driver');
    await page.waitForFunction(() => !document.querySelector('.recruitment-loading') && document.querySelectorAll('.recruitment-worklist tbody tr').length === 1);
    assert.equal(await page.locator('.recruitment-worklist tbody tr').count(), 1);
    await page.getByLabel('Направление', { exact: true }).selectOption('');

    await page.getByRole('button', { name: candidate.fullName, exact: true }).click();
    await form().getByRole('button', { name: 'Изменить этап', exact: true }).click();
    await form().getByLabel('Этап подбора', { exact: true }).selectOption('hired');
    await form().getByLabel('Дата выхода в работу', { exact: true }).fill('2026-09-17');
    application = await save('applications');
    assert.equal(application.stage, 'hired');
    await form().getByText('Собеседование → Выход в работу', { exact: true }).waitFor();
    await form().getByRole('button', { name: 'Закрыть карточку', exact: true }).click();
    await tabs.getByRole('button', { name: 'Аналитика', exact: true }).click();
    await page.getByRole('heading', { name: 'Дошли до этапа', exact: true }).waitFor();
    await page.getByRole('heading', { name: 'Смены и удержание водителей', exact: true }).waitFor();
    assert.equal((await snapshot()).events.length, 2, 'no imaginary transitions for skipped stages');
    await page.screenshot({ path: path.join(out, 'analytics-desktop.png'), fullPage: true });

    const publication = new Date().toISOString();
    demand = (await fixture.request('PUT', '/recruitment/requests', { ...demand, publishedAt: publication }, session.accessToken)).body;
    await page.getByRole('button', { name: 'Обновить', exact: true }).click();
    await tabs.getByRole('button', { name: 'Потребности', exact: true }).click();
    await page.getByRole('button', { name: 'Изменить потребность', exact: true }).click();
    await form().getByLabel('Комментарий к потребности', { exact: true }).fill('Уточнены условия');
    demand = await save('requests');
    assert.equal(demand.publishedAt, publication, 'editing notes preserves exact publication timestamp');

    await tabs.getByRole('button', { name: 'Кандидаты', exact: true }).click();
    await page.getByRole('button', { name: 'Список', exact: true }).click();
    await page.getByRole('button', { name: candidate.fullName, exact: true }).click();
    await form().getByRole('button', { name: 'Изменить кандидата', exact: true }).click();
    await form().getByLabel('Заметки о кандидате', { exact: true }).fill('Несохранённая заметка');
    acceptLeave = false;
    const previousDialogs = dialogCount;
    await form().getByRole('button', { name: 'Закрыть', exact: true }).click();
    assert.equal(dialogCount, previousDialogs + 1);
    assert.equal(await form().getByLabel('Заметки о кандидате', { exact: true }).inputValue(), 'Несохранённая заметка');
    const current = (await snapshot()).candidates.find(item => item.id === candidate.id);
    assert.equal((await fixture.request('PUT', '/recruitment/candidates', { ...current, district: 'Изменено другим менеджером' }, session.accessToken)).status, 200);
    await save('candidates', 409);
    await form().getByRole('alert').waitFor();
    assert.equal(await form().getByLabel('Заметки о кандидате', { exact: true }).inputValue(), 'Несохранённая заметка');
    acceptLeave = true;
    await form().getByRole('button', { name: 'Закрыть', exact: true }).click();
    await form().getByRole('button', { name: 'Закрыть карточку', exact: true }).click();
    await page.reload();
    await page.getByRole('heading', { name: 'Рекрутинг', exact: true }).waitFor();
    await tabs.getByRole('button', { name: 'Кандидаты', exact: true }).click();
    await page.getByRole('button', { name: 'Список', exact: true }).click();
    await page.getByRole('button', { name: candidate.fullName, exact: true }).waitFor();
    await page.screenshot({ path: path.join(out, 'candidates-desktop.png'), fullPage: true });
    await page.locator('.theme-switcher select').selectOption('dark');
    await page.screenshot({ path: path.join(out, 'candidates-dark.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'candidate page fits mobile');
    await page.screenshot({ path: path.join(out, 'candidates-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: carrier.fullName, exact: true }).click();
    await form().getByRole('button', { name: 'Изменить кандидата', exact: true }).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'candidate form fits mobile');
    await page.screenshot({ path: path.join(out, 'candidate-form-mobile.png') });
    await form().getByLabel('Грузоподъёмность / объём', { exact: true }).fill('2 т / 14 м³');
    const mobileCarrier = await save('candidates');
    assert.equal(mobileCarrier.vehicleCapacity, '2 т / 14 м³', 'lower mobile form controls and submit are reachable');
    await form().getByRole('button', { name: 'Закрыть карточку', exact: true }).click();
    console.log('PASS carrier vehicle fields, filters, stage history, analytics, timestamps, conflicts, reload, themes and mobile');

    await fixture.adminPool.query('UPDATE access_grants SET personal_data_visible=false WHERE user_id=$1', [fixture.ids.dispatcher]);
    await page.getByRole('button', { name: 'Обновить', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Нет доступа' }).waitFor();
    assert.equal(await page.locator('.recruitment-worklist tbody tr').count(), 0);
    console.log('PASS revoked personal-data access clears candidate data');

    assert.deepEqual(errors, []);
  } finally {
    if (browser) await browser.close();
    await fixture.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
