'use strict';
// End-to-end checks against a disposable database; no workplace messages.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { createTestServer } = require('./local-test-server.cjs');
const { articleStructure, createArticlePosition } = require('./team-article-fixtures.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const fixture = await createTestServer({ staffTeamActors: true, builtFrontend: process.env.TEAM_BUILT_FRONTEND === 'true' });
  let browser, releaseInitialSchedules;
  try {
    const { ids, request, devLogin } = fixture;
    await fixture.adminPool.query('UPDATE access_grants SET personal_data_visible=true');
    const admin = await devLogin(ids.admin), employee = await devLogin(ids.drivers[0]), peer = await devLogin(ids.drivers[1]);
    const scope = ids.scope;
    const api = async (method, route, body, session = admin) => {
      const result = await request(method, route, body, session.accessToken);
      assert.ok([200, 201].includes(result.status), `${route}: ${JSON.stringify(result.body)}`);
      return result.body;
    };
    const channel = await api('POST', '/team/conversations', { id: randomUUID(), responsibilityScopeId: scope, kind: 'channel', title: 'Логистика и развитие', memberIds: [] });
    const root = await api('POST', '/team/messages', { id: randomUUID(), responsibilityScopeId: scope, conversationId: channel.id, parentId: null, text: 'Задача: проверить документы до пятницы.' }, employee);
    const reply = await api('POST', '/team/messages', { id: randomUUID(), responsibilityScopeId: scope, conversationId: channel.id, parentId: root.id, text: 'Можно автоматизировать сверку и сократить время.' }, peer);
    await api('POST', '/team/messages', { id: randomUUID(), responsibilityScopeId: scope, conversationId: channel.id, parentId: reply.id, text: 'Рост: новый клиент готов увеличить объём.' }, employee);
    const direct = await api('POST', '/team/conversations', { id: randomUUID(), responsibilityScopeId: scope, kind: 'direct', title: 'Личный чат', memberIds: [ids.drivers[0], ids.drivers[1]] }, employee);
    await api('POST', '/team/messages', { id: randomUUID(), responsibilityScopeId: scope, conversationId: direct.id, text: 'Риск: поставка задерживается, нужно проверить срок.', parentId: null }, employee);
    const articlePosition = await createArticlePosition(fixture, admin);
    await api('PUT', '/team/articles', { id: randomUUID(), responsibilityScopeId: scope, title: 'Регламент проверки документов', body: 'Проверяйте реквизиты и согласованный срок до отправки.', version: 0, ...articleStructure(articlePosition) });
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const errors = [], output = path.resolve(__dirname, '../.local/team-browser-qa');
    await fs.mkdir(output, { recursive: true });
    async function pageFor(session, viewport = { width: 1440, height: 1000 }) {
      const context = await browser.newContext({ viewport, timezoneId: 'Europe/Moscow' });
      await context.addInitScript(value => sessionStorage.setItem('ecl.session.v2', JSON.stringify({ session: value })), { ...session, rememberedDevice: false });
      const page = await context.newPage();
      page.setDefaultTimeout(15000);
      page.on('pageerror', error => errors.push(error.message));
      await page.goto(`${fixture.origin}/?section=team`);
      await page.getByRole('heading', { name: 'Команда', exact: true }).waitFor();
      return page;
    }
    const page = await pageFor(admin);
    page.on('dialog', dialog => dialog.accept());
    await page.getByText('Логистика и развитие', { exact: true }).first().click();
    await page.getByText(root.text, { exact: true }).waitFor();
    await page.getByRole('button', { name: `Открыть ветку: ${root.text.slice(0, 60)}`, exact: true }).click();
    const threadPanel = page.getByRole('complementary', { name: 'Ветка обсуждения' });
    await threadPanel.getByText(reply.text, { exact: true }).waitFor();
    await threadPanel.getByRole('button', { name: `Открыть ветку: ${reply.text.slice(0, 60)}`, exact: true }).click();
    await threadPanel.getByText('Рост: новый клиент готов увеличить объём.', { exact: true }).waitFor();
    await threadPanel.getByLabel('Ответ в ветке', { exact: true }).fill('Задача: подготовить предложение новому клиенту.');
    await threadPanel.getByRole('button', { name: 'Отправить', exact: true }).click();
    await threadPanel.getByText('Задача: подготовить предложение новому клиенту.', { exact: true }).waitFor();
    await page.screenshot({ path: path.join(output, 'channels-desktop.png'), fullPage: true });
    await page.getByRole('button', { name: 'Закрыть ветку', exact: true }).click();
    await page.getByRole('button', { name: 'Создать канал', exact: true }).click();
    let dialog = page.getByRole('dialog');
    await dialog.getByLabel('Название канала', { exact: true }).fill('Решения команды');
    await dialog.getByRole('button', { name: 'Создать канал', exact: true }).click();
    await page.getByRole('heading', { name: '# Решения команды', exact: true }).waitFor();
    await page.getByLabel('Сообщение в чат', { exact: true }).fill('Оптимизация: автоматизируем сверку документов.');
    await page.getByRole('button', { name: 'Отправить', exact: true }).click();
    await page.getByText('Оптимизация: автоматизируем сверку документов.', { exact: true }).waitFor();
    const tabs = page.getByRole('navigation', { name: 'Разделы команды' });
    await tabs.getByRole('button', { name: 'База знаний', exact: true }).click();
    await page.getByRole('button', { name: 'Новая статья', exact: true }).click();
    await page.getByLabel('Тема', { exact: true }).fill('Как проверять договор');
    const structure = articleStructure(articlePosition);
    await page.getByLabel('Причина создания', { exact: true }).fill(structure.reason);
    await page.getByLabel('Задача создания', { exact: true }).fill(structure.purpose);
    await page.getByLabel('Текст', { exact: true }).fill('Проверьте реквизиты, суммы и срок поставки.');
    await page.getByLabel('Результат', { exact: true }).fill(structure.result);
    await page.getByLabel('Для кого', { exact: true }).selectOption(articlePosition);
    await page.getByRole('button', { name: 'Сохранить статью', exact: true }).click();
    await page.getByRole('heading', { name: 'Как проверять договор', exact: true }).waitFor();
    const earlierSummary = await api('POST', '/team/summaries', { responsibilityScopeId: scope,
      periodStart: new Date(Date.now() - 3 * 86400000).toISOString(), periodEnd: new Date(Date.now() - 2 * 86400000).toISOString() });
    const earlierSchedule = await api('PUT', '/team/schedules', { id: randomUUID(), responsibilityScopeId: scope,
      enabled: false, frequency: 'daily', time: '08:05', timeZone: 'Europe/Moscow', weekday: 1, recipientIds: [] });
    // A summary can be created while an unrelated initial list is still loading.
    // Its mutation must neither discard the people/chat lists nor be overwritten by the older read.
    const schedulesPath = url => url.pathname === '/api/v1/team/schedules' && url.searchParams.has('responsibilityScopeId') && url.searchParams.get('reportKind') !== 'fleet_release';
    const initialSchedulesGate = new Promise(resolve => { releaseInitialSchedules = resolve; });
    let captureScheduleSnapshot, rejectScheduleSnapshot;
    const scheduleSnapshot = new Promise((resolve, reject) => { captureScheduleSnapshot = resolve; rejectScheduleSnapshot = reject; });
    const initialSchedulesRequest = page.waitForRequest(request => schedulesPath(new URL(request.url())));
    await page.route(schedulesPath, async route => {
      try {
        const response = await route.fetch();
        captureScheduleSnapshot(await response.json());
        await initialSchedulesGate;
        await route.fulfill({ response });
      } catch (error) { rejectScheduleSnapshot(error); throw error; }
    });
    await page.reload();
    await page.getByRole('heading', { name: 'Команда', exact: true }).waitFor();
    await tabs.getByRole('button', { name: 'База знаний', exact: true }).click();
    await page.getByText('Как проверять договор', { exact: true }).first().click();
    await page.getByText('Проверьте реквизиты, суммы и срок поставки.', { exact: true }).waitFor();
    await page.goto(`${fixture.origin}/?section=neural`);
    await initialSchedulesRequest;
    assert.deepEqual((await scheduleSnapshot).schedules.map(item => item.id), [earlierSchedule.id]);
    await page.getByRole('heading', { name: 'Сводка сообщений', exact: true }).waitFor();
    const summaryTabs = page.getByRole('navigation', { name: 'Разделы сводок' });
    await summaryTabs.getByRole('button', { name: 'Сводки', exact: true }).click();
    const end = new Date(Math.ceil(Date.now() / 60000) * 60000);
    const moscow = new Date(end.getTime() + 3 * 3600000).toISOString().slice(0, 16);
    await page.getByLabel('Окончание периода', { exact: true }).fill(moscow);
    await page.getByRole('button', { name: 'Создать сводку', exact: true }).click();
    await page.getByRole('button', { name: 'Поделиться', exact: true }).waitFor();
    await page.locator('.team-summary-category.is-risk').getByText('Риск: поставка задерживается, нужно проверить срок.', { exact: true }).waitFor();
    await summaryTabs.getByRole('button', { name: 'Расписание сводок', exact: true }).click();
    await page.getByRole('button', { name: 'Добавить расписание', exact: true }).click();
    await page.getByLabel('Периодичность', { exact: true }).selectOption('weekly');
    await page.getByLabel('День недели', { exact: true }).selectOption('5');
    await page.getByLabel('Время', { exact: true }).fill('09:30');
    await page.getByRole('button', { name: 'Сохранить расписание', exact: true }).click();
    await page.getByRole('heading', { name: 'Еженедельно в 09:30', exact: true }).waitFor();
    assert.equal(await page.locator('.team-tabs-meta').innerText(), 'Загрузка…');
    const initialSchedulesResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/team/schedules');
    releaseInitialSchedules();
    assert.equal((await initialSchedulesResponse).status(), 200);
    await page.unroute(schedulesPath);
    await page.getByRole('heading', { name: 'Ежедневно в 08:05', exact: true }).waitFor();
    assert.equal(await page.getByRole('heading', { name: 'Еженедельно в 09:30', exact: true }).count(), 1);
    await summaryTabs.getByRole('button', { name: 'Сводки', exact: true }).click();
    await page.locator('.team-summary-workspace .team-library-sidebar').getByText(earlierSummary.title, { exact: true }).waitFor();
    assert.equal(await page.locator('.team-summary-workspace .team-library-sidebar .team-article-item').count(), 2);
    await page.locator('.team-summary-category.is-risk').getByText('Риск: поставка задерживается, нужно проверить срок.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Поделиться', exact: true }).click();
    await page.getByRole('group', { name: 'Кому доступна сводка' }).getByRole('checkbox', { name: 'Диспетчер', exact: true }).check();
    await page.getByRole('button', { name: 'Сохранить доступ', exact: true }).click();
    await page.getByText('Доступ к сводке обновлён.', { exact: true }).waitFor();
    await page.locator('.team-summary-category.is-risk details summary').first().click();
    await page.locator('.team-summary-category.is-risk').getByRole('button', { name: /^Открыть источник / }).first().click();
    dialog = page.getByRole('dialog', { name: 'Источник сводки', exact: true });
    await dialog.getByText('Риск: поставка задерживается, нужно проверить срок.', { exact: true }).waitFor();
    await dialog.getByRole('button', { name: 'Закрыть', exact: true }).click();
    await page.screenshot({ path: path.join(output, 'summary-desktop.png'), fullPage: true });
    const recipient = await pageFor(await devLogin(ids.dispatcher));
    await recipient.goto(`${fixture.origin}/?section=neural`);
    await recipient.getByRole('navigation', { name: 'Разделы сводок' }).getByRole('button', { name: 'Сводки', exact: true }).click();
    await recipient.locator('.team-summary-category.is-risk').getByText('Риск: поставка задерживается, нужно проверить срок.', { exact: true }).waitFor();
    assert.equal(await recipient.getByRole('button', { name: 'Создать сводку', exact: true }).count(), 0);
    assert.equal(await recipient.getByRole('button', { name: 'Расписание сводок', exact: true }).count(), 0);
    await recipient.locator('.team-summary-category.is-risk details summary').first().click();
    await recipient.locator('.team-summary-category.is-risk').getByRole('button', { name: /^Открыть источник / }).first().click();
    await recipient.getByText('Исходное сообщение недоступно: сводка не предоставляет доступ к чужой переписке. Текст сводки остаётся доступным.', { exact: true }).waitFor();
    assert.equal(await recipient.getByRole('dialog').count(), 0);
    await summaryTabs.getByRole('button', { name: 'Расписание сводок', exact: true }).click();
    await page.getByRole('heading', { name: 'Еженедельно в 09:30', exact: true }).waitFor();
    const scheduleState = await api('GET', `/team/schedules?responsibilityScopeId=${scope}`);
    assert.equal(scheduleState.schedules.length, 2);
    assert.equal(scheduleState.schedules.find(item => item.id !== earlierSchedule.id).weekday, 5);
    const employeePage = await pageFor(employee);
    await employeePage.getByRole('button', { name: 'Новый личный чат', exact: true }).click();
    dialog = employeePage.getByRole('dialog');
    await dialog.getByLabel('Собеседник', { exact: true }).selectOption(ids.mechanic);
    await dialog.getByRole('button', { name: 'Открыть чат', exact: true }).click();
    await employeePage.getByLabel('Сообщение в чат', { exact: true }).fill('Коллега, подтвердите получение документов.');
    await employeePage.getByRole('button', { name: 'Отправить', exact: true }).click();
    await employeePage.getByText('Коллега, подтвердите получение документов.', { exact: true }).waitFor();
    await page.goto(`${fixture.origin}/?section=team`);
    await tabs.getByRole('button', { name: 'Обсуждения', exact: true }).click();
    await page.getByText('Логистика и развитие', { exact: true }).first().click();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile layout must not scroll sideways');
    await page.screenshot({ path: path.join(output, 'channels-mobile.png'), fullPage: true });
    // More than one page arriving between polls must remain reachable backwards.
    await page.bringToFront();
    await fixture.adminPool.query(`INSERT INTO team_messages(id,legal_entity_id,region_id,project_id,responsibility_scope_id,conversation_id,parent_id,text,author_id,author_name)
      SELECT gen_random_uuid(),$1,$2,$3,$4,$5,NULL,'Сообщение потока '||n,$6,'Диспетчер' FROM generate_series(1,105) n`, [ids.legal, ids.region, ids.project, scope, channel.id, ids.dispatcher]);
    await page.getByText('Сообщение потока 105', { exact: true }).waitFor({ timeout: 20000 });
    await page.getByRole('button', { name: 'Загрузить предыдущие сообщения', exact: true }).click();
    await page.getByText('Сообщение потока 1', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log('PASS team browser: channels, nested branches, sending, direct chat, knowledge persistence, summary/sharing, recipient restrictions, weekly schedule, desktop/mobile, no JavaScript errors');
  } finally { releaseInitialSchedules?.(); if (browser) await browser.close(); await fixture.close(); }
})().catch(error => { console.error(error.stack || error.message); process.exit(1); });
