'use strict';
// Real browser + HTTP API + disposable PostgreSQL; synthetic employees only.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { createTestServer } = require('./local-test-server.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const fixture = await createTestServer({ builtFrontend: process.env.TENDERS_BUILT_FRONTEND === 'true' });
  const out = path.resolve(__dirname, '../.local/tenders-browser-qa');
  let browser;
  try {
    await fs.mkdir(out, { recursive: true });
    const admin = await fixture.devLogin(fixture.ids.admin);
    const issued = await fixture.request('POST', `/access/users/${fixture.ids.admin}/password`, { phone: '+79990008521' }, admin.accessToken);
    assert.equal(issued.status, 201);
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    await page.goto(fixture.origin);
    await page.locator('#login-phone').fill('+79990008521');
    await page.locator('#login-password').fill(issued.body.password);
    await page.getByRole('button', { name: 'Войти', exact: true }).click();
    await page.getByRole('heading', { name: 'Сотрудники', exact: true }).waitFor();
    const navigation = page.getByRole('navigation', { name: 'Разделы', exact: true });
    await navigation.getByRole('button', { name: 'Тендеры', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Добавить тендерного специалиста', exact: true }).click();
    const form = page.getByRole('form', { name: 'Добавить тендерного специалиста', exact: true });
    await form.getByLabel('Имя сотрудника', { exact: true }).fill('Синтетический специалист браузера');
    await form.getByLabel('Область работы', { exact: true }).selectOption(fixture.ids.scope);
    const createdResponse = page.waitForResponse(response => response.url().endsWith('/access/employees/tender-specialist') && response.request().method() === 'POST');
    await form.getByRole('button', { name: 'Создать сотрудника', exact: true }).click();
    const created = await createdResponse;
    assert.equal(created.status(), 201);
    const employee = await created.json();
    assert.equal(employee.role, 'tender_specialist');
    assert.equal(employee.sourceKind, 'internal_manual');
    await page.getByRole('heading', { name: 'Выдать доступ по телефону', exact: true }).waitFor();
    await page.getByRole('button', { name: 'К списку', exact: true }).click();
    const card = page.locator('article.employee-card').filter({ hasText: employee.employeeNumber });
    await card.getByText(/^Тендерный специалист/).waitFor();
    await page.screenshot({ path: path.join(out, 'administrator-specialist.png'), fullPage: true });
    const impersonationResponse = page.waitForResponse(response => response.url().endsWith('/auth/impersonate') && response.request().method() === 'POST');
    await card.getByRole('button', { name: 'Войти как сотрудник', exact: true }).click();
    const impersonation = await impersonationResponse;
    assert.equal(impersonation.status(), 200);
    const child = await impersonation.json();
    assert.equal(child.actor.role, 'tender_specialist');
    await page.getByRole('heading', { name: 'Тендеры', exact: true }).waitFor();
    assert.equal(await navigation.getByRole('button', { name: 'Тендеры', exact: true }).getAttribute('aria-current'), 'page');
    for (const label of ['Сотрудники', 'Планирование', 'Рекрутинг', 'Рейсы', 'Финансы и 1С', 'Связь с отделами']) {
      assert.equal(await navigation.getByRole('button', { name: label, exact: true }).count(), 0, `Specialist must not see ${label}`);
    }
    console.log('PASS administrator creates a named specialist, password handoff appears, impersonation opens only Tenders');

    await page.getByRole('button', { name: '+ Новый тендер', exact: true }).first().click();
    const createDialog = page.getByRole('dialog', { name: 'Новый тендер', exact: true });
    const title = 'Синтетическая доставка по Москве';
    await createDialog.getByLabel('Название заказчика', { exact: true }).fill('Синтетический заказчик браузера');
    await createDialog.getByLabel('Название тендера или проекта', { exact: true }).fill(title);
    await createDialog.getByLabel('Количество авто', { exact: true }).fill('5–8');
    await createDialog.getByLabel('Требования к автомобилям и работе', { exact: true }).fill('8 паллет, рефрижератор');
    await createDialog.getByLabel('Тип доставки', { exact: true }).selectOption('crew');
    await createDialog.getByLabel('Ожидаемый запуск', { exact: true }).fill('2026-10-15');
    await createDialog.getByLabel('Дедлайн подачи заявки', { exact: true }).fill('2026-10-01');
    await createDialog.getByLabel('Следующий шаг', { exact: true }).fill('Уточнить тариф');
    const tenderResponse = page.waitForResponse(response => response.url().endsWith('/tenders/items') && response.request().method() === 'PUT');
    await createDialog.getByRole('button', { name: 'Сохранить', exact: true }).click();
    const tenderCreated = await tenderResponse;
    assert.equal(tenderCreated.status(), 200);
    const tender = await tenderCreated.json();
    await createDialog.waitFor({ state: 'hidden' });
    const tenderCard = page.locator('article.tenders-card').filter({ hasText: title });
    await tenderCard.waitFor();
    const importedNote = 'Синтетическая исходная заметка: дату и автора исходной записи установить нельзя.';
    const importedEventId = randomUUID();
    await fixture.adminPool.query(`INSERT INTO tender_events(id,legal_entity_id,region_id,project_id,responsibility_scope_id,
      tender_id,customer_id,type,text,actor_id,actor_name)
      SELECT $1,legal_entity_id,region_id,project_id,responsibility_scope_id,id,customer_id,'import',$2,$3,$4
      FROM tender_items WHERE id=$5`, [importedEventId, importedNote, employee.id, 'Синтетический оператор переноса', tender.id]);
    await page.locator('.tenders-workspace').getByRole('button', { name: 'Обновить', exact: true }).click();
    await tenderCard.locator('.tenders-last-comment p').filter({ hasText: importedNote }).waitFor();
    await tenderCard.getByText('Исходная заметка · дата неизвестна', { exact: true }).waitFor();
    assert.match(await tenderCard.locator('.tenders-last-comment small').innerText(), /^Перенесено /);
    const importedSnapshot = await fixture.request('GET', `/tenders?responsibilityScopeId=${fixture.ids.scope}`, undefined, child.accessToken);
    assert.equal(importedSnapshot.status, 200);
    assert.equal(importedSnapshot.body.events.filter(event => event.id === importedEventId && event.type === 'import').length, 1);
    assert.equal(importedSnapshot.body.events.filter(event => event.type === 'comment').length, 0, 'Imported notes are not new specialist comments');
    await page.getByRole('button', { name: 'Таблица', exact: true }).click();
    const importedRow = page.getByRole('table', { name: 'Тендеры', exact: true }).getByRole('row').filter({ hasText: title });
    await importedRow.getByText(importedNote, { exact: true }).waitFor();
    await importedRow.getByText('Исходная заметка · дата неизвестна', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Канбан', exact: true }).click();
    await tenderCard.waitFor();
    const stageResponse = page.waitForResponse(response => response.url().endsWith('/tenders/items') && response.request().method() === 'PUT');
    await tenderCard.getByLabel(`Статус: ${title}`, { exact: true }).selectOption('in_progress');
    assert.equal((await stageResponse).status(), 200);
    assert.equal(await tenderCard.locator('.tenders-last-comment p').innerText(), importedNote, 'A status event does not replace the imported-note fallback');
    const firstComment = 'Согласовали технические требования';
    await tenderCard.getByLabel(`Новый комментарий: ${title}`, { exact: true }).fill(firstComment);
    const commentResponse = page.waitForResponse(response => response.url().endsWith('/tenders/comments') && response.request().method() === 'POST');
    await tenderCard.getByRole('button', { name: 'Добавить комментарий', exact: true }).click();
    assert.equal((await commentResponse).status(), 201);
    await tenderCard.locator('.tenders-last-comment p').filter({ hasText: firstComment }).waitFor();
    assert.equal(await tenderCard.getByText('Исходная заметка · дата неизвестна', { exact: true }).count(), 0, 'A real comment replaces the fallback on the board');
    await tenderCard.getByLabel(`Статус: ${title}`, { exact: true }).selectOption('won');
    const won = page.getByRole('dialog', { name: 'Выиграно', exact: true });
    await won.getByLabel('Что выиграно и на каких условиях', { exact: true }).fill('Подтверждены 5 машин на первый этап');
    await won.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await won.waitFor({ state: 'hidden' });
    assert.equal(await tenderCard.locator('.tenders-last-comment p').innerText(), firstComment);
    await tenderCard.getByRole('button', { name: 'Карточка и история →', exact: true }).click();
    const detail = page.getByRole('dialog', { name: title, exact: true });
    await detail.getByText(firstComment, { exact: true }).waitFor();
    await detail.getByText(importedNote, { exact: true }).waitFor();
    await detail.getByText('Исходная заметка · дата неизвестна', { exact: true }).waitFor();
    await detail.getByRole('button', { name: 'Весь заказчик', exact: true }).click();
    const secondComment = 'Дата запуска подтверждена заказчиком';
    await detail.getByLabel(`Новый комментарий: ${title}`, { exact: true }).fill(secondComment);
    await detail.getByRole('button', { name: 'Добавить комментарий', exact: true }).click();
    await detail.locator('.tenders-history li.is-comment p').filter({ hasText: secondComment }).waitFor();
    assert.deepEqual(await detail.locator('.tenders-history li.is-comment p').allTextContents(), [firstComment, secondComment]);
    await detail.getByRole('button', { name: 'Закрыть окно', exact: true }).click();
    assert.equal(await tenderCard.locator('.tenders-last-comment p').innerText(), secondComment);
    console.log('PASS customer and tender creation, inline status and comments, reasons, chronological customer/card history');

    const tableButton = page.getByRole('button', { name: 'Таблица', exact: true });
    const boardButton = page.getByRole('button', { name: 'Канбан', exact: true });
    const table = page.getByRole('table', { name: 'Тендеры', exact: true });
    const tableRow = table.getByRole('row').filter({ hasText: title });
    const columnSettings = page.getByRole('region', { name: 'Настройка колонок', exact: true });
    const headerNames = async () => (await table.getByRole('columnheader').allTextContents()).map(text => text.trim());
    await tableButton.click();
    await table.waitFor();
    await tableRow.waitFor();
    assert.equal(await tableButton.getAttribute('aria-pressed'), 'true');
    assert.equal(await boardButton.getAttribute('aria-pressed'), 'false');
    assert.equal(await tableRow.count(), 1);
    assert.equal(await tenderCard.count(), 0, 'Only the selected view is displayed');
    const defaultHeaders = await headerNames();
    for (const label of ['Заказчик / тендер', 'Статус', 'Количество авто', 'Требования', 'Последний комментарий', 'Тип доставки', 'Запуск']) {
      assert.ok(defaultHeaders.includes(label), `Default table includes ${label}`);
    }
    await tableRow.getByText(secondComment, { exact: true }).waitFor();
    assert.equal(await tableRow.getByText(importedNote, { exact: true }).count(), 0, 'The table shows the actual comment after import');
    assert.equal(await tableRow.getByText('Исходная заметка · дата неизвестна', { exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Колонки', exact: true }).click();
    const requiredColumn = columnSettings.getByRole('checkbox', { name: 'Заказчик / тендер', exact: true });
    assert.equal(await requiredColumn.isChecked(), true);
    assert.equal(await requiredColumn.isDisabled(), true, 'The identifying column cannot be hidden');
    await columnSettings.getByRole('checkbox', { name: 'Тип доставки', exact: true }).uncheck();
    await columnSettings.getByRole('checkbox', { name: 'Следующий шаг', exact: true }).check();
    assert.equal(await table.getByRole('columnheader', { name: 'Тип доставки', exact: true }).count(), 0);
    await table.getByRole('columnheader', { name: 'Следующий шаг', exact: true }).waitFor();
    await tableRow.getByText('Уточнить тариф', { exact: true }).waitFor();
    await columnSettings.getByRole('button', { name: 'Готово', exact: true }).click();
    await columnSettings.waitFor({ state: 'hidden' });
    const customizedHeaders = await headerNames();
    await page.reload();
    await tableRow.waitFor();
    assert.equal(await tableButton.getAttribute('aria-pressed'), 'true', 'Table preference survives reload');
    assert.deepEqual(await headerNames(), customizedHeaders, 'Column preferences survive reload');
    assert.equal(await tableRow.getByLabel(`Статус: ${title}`, { exact: true }).inputValue(), 'won');
    await tableRow.getByText(secondComment, { exact: true }).waitFor();

    await page.getByRole('button', { name: 'Колонки', exact: true }).click();
    assert.equal(await columnSettings.getByRole('checkbox', { name: 'Тип доставки', exact: true }).isChecked(), false);
    assert.equal(await columnSettings.getByRole('checkbox', { name: 'Следующий шаг', exact: true }).isChecked(), true);
    await columnSettings.getByRole('checkbox', { name: 'Тип доставки', exact: true }).check();
    await table.getByRole('columnheader', { name: 'Тип доставки', exact: true }).waitFor();
    await columnSettings.getByRole('checkbox', { name: 'Требования', exact: true }).uncheck();
    assert.equal(await table.getByRole('columnheader', { name: 'Требования', exact: true }).count(), 0);
    await columnSettings.getByRole('button', { name: 'По умолчанию', exact: true }).click();
    assert.deepEqual(await headerNames(), defaultHeaders, 'Reset restores the original visible columns');
    await columnSettings.getByRole('button', { name: 'Готово', exact: true }).click();

    const tableComment = 'Комментарий из таблицы без повторного создания тендера';
    await tableRow.getByRole('button', { name: `Написать комментарий: ${title}`, exact: true }).click();
    await tableRow.getByLabel(`Новый комментарий: ${title}`, { exact: true }).fill(tableComment);
    await boardButton.click();
    await tenderCard.waitFor();
    assert.equal(await tenderCard.getByLabel(`Новый комментарий: ${title}`, { exact: true }).inputValue(), tableComment, 'Switching views preserves the comment draft');
    await tableButton.click();
    await tableRow.waitFor();
    assert.equal(await tableRow.getByLabel(`Новый комментарий: ${title}`, { exact: true }).inputValue(), tableComment);
    const tableCommentResponse = page.waitForResponse(response => response.url().endsWith('/tenders/comments') && response.request().method() === 'POST');
    await tableRow.getByRole('button', { name: 'Добавить комментарий', exact: true }).click();
    const addedTableComment = await tableCommentResponse;
    assert.equal(addedTableComment.status(), 201);
    assert.equal((await addedTableComment.json()).tenderId, tender.id);
    await tableRow.getByText(tableComment, { exact: true }).waitFor();
    const tableStageResponse = page.waitForResponse(response => response.url().endsWith('/tenders/items') && response.request().method() === 'PUT');
    await tableRow.getByLabel(`Статус: ${title}`, { exact: true }).selectOption('in_progress');
    const updatedFromTable = await tableStageResponse;
    assert.equal(updatedFromTable.status(), 200);
    assert.equal((await updatedFromTable.json()).id, tender.id);
    await tableRow.getByText(tableComment, { exact: true }).waitFor();
    await tableRow.getByLabel(`Статус: ${title}`, { exact: true }).selectOption('won');
    await won.waitFor();
    assert.equal(await won.getByLabel('Что выиграно и на каких условиях', { exact: true }).inputValue(), 'Подтверждены 5 машин на первый этап');
    await won.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await won.waitFor({ state: 'hidden' });
    await tableRow.getByText(tableComment, { exact: true }).waitFor();
    const afterTable = await fixture.request('GET', `/tenders?responsibilityScopeId=${fixture.ids.scope}`, undefined, child.accessToken);
    assert.equal(afterTable.status, 200);
    assert.deepEqual(afterTable.body.tenders.map(item => item.id), [tender.id], 'Both views update the same tender without creating duplicates');
    assert.equal(afterTable.body.customers.length, 1);
    assert.equal(afterTable.body.tenders[0].status, 'won');
    assert.deepEqual(afterTable.body.events.filter(event => event.tenderId === tender.id && event.type === 'comment').map(event => event.text), [firstComment, secondComment, tableComment]);
    await page.screenshot({ path: path.join(out, 'tenders-table-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Table scroll stays inside its container on mobile');
    await page.screenshot({ path: path.join(out, 'tenders-table-mobile.png'), fullPage: true });
    await boardButton.click();
    await tenderCard.waitFor();
    assert.equal(await tenderCard.locator('.tenders-last-comment p').innerText(), tableComment);
    await page.setViewportSize({ width: 1440, height: 1000 });
    console.log('PASS table/kanban switch, hide/show/reset columns, persisted view preferences, shared drafts and records, table actions and mobile overflow');

    await page.screenshot({ path: path.join(out, 'tenders-desktop.png'), fullPage: true });
    await page.reload();
    await page.getByRole('heading', { name: 'Тендеры', exact: true }).waitFor();
    await tenderCard.locator('.tenders-last-comment p').filter({ hasText: tableComment }).waitFor();
    assert.equal(await boardButton.getAttribute('aria-pressed'), 'true', 'Kanban preference survives reload');
    assert.equal(await tenderCard.getByLabel(`Статус: ${title}`, { exact: true }).inputValue(), 'won');
    await page.locator('.theme-switcher select').selectOption('dark');
    await page.screenshot({ path: path.join(out, 'tenders-dark.png'), fullPage: true });
    await page.locator('.theme-switcher select').selectOption('light');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Tender workspace fits mobile');
    await page.screenshot({ path: path.join(out, 'tenders-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Вернуться в админку', exact: true }).click();
    await page.getByRole('heading', { name: 'Сотрудники', exact: true }).waitFor();
    assert.equal((await fixture.request('GET', '/me', undefined, child.accessToken)).status, 401);
    assert.deepEqual(errors, []);
    console.log('PASS reload, mobile navigation and return to administrator; child session revoked; no browser errors');

    const freshAdmin = await fixture.devLogin(fixture.ids.admin);
    const credentials = await fixture.request('POST', `/access/users/${employee.id}/password`, { phone: '+79990008522' }, freshAdmin.accessToken);
    assert.equal(credentials.status, 201);
    const ownContext = await browser.newContext({ viewport: { width: 1280, height: 900 } });
    const ownPage = await ownContext.newPage();
    ownPage.on('pageerror', error => errors.push(error.message));
    await ownPage.goto(fixture.origin);
    await ownPage.locator('#login-phone').fill('+79990008522');
    await ownPage.locator('#login-password').fill(credentials.body.password);
    await ownPage.getByRole('button', { name: 'Войти', exact: true }).click();
    await ownPage.getByRole('heading', { name: 'Тендеры', exact: true }).waitFor();
    await ownPage.locator('.tenders-card').filter({ hasText: title }).waitFor();
    assert.deepEqual(errors, []);
    await ownContext.close();
    console.log('PASS specialist phone/password login opens saved tender workspace');
  } finally {
    if (browser) await browser.close();
    await fixture.close();
  }
})().catch(error => { console.error(error); process.exit(1); });
